data_path: data/datasets/additions_chain_of_thought_template_0.0_0.0_0.0
dnl: 0.0
enl: 0.0
epoch: 100
epochs: 100
model: gpt2
model_path: gpt2
prompt_template: chain_of_thought_template
snl: 0.0
sparsity_modes:
- agglomerative
- agglomerative
- agglomerative
- agglomerative
- agglomerative
sparsity_scheme:
- 2
- 10
- 25
- 45
- 70
task: additions
tok: gpt2
tok_path: gpt2
