data_path: data/datasets/additions_simple_template_0.0_0.0_0.0
dnl: 0.0
enl: 0.0
epoch: 100
epochs: 100
model: gpt2
model_path: gpt2
prompt_template: simple_template
snl: 0.0
task: additions
tok: gpt2
tok_path: gpt2
