e1:
  models: [gpt2]
  toks: [gpt2]
  tasks: [additions]
  prompt_templates: [chain_of_thought_template]
  dnls: [0.0]
  snls: [0.0]
  enls: [0.0]
  epochs: [100]
  sparsity_modes: [[random, random, random, random, random], [agglomerative, agglomerative, agglomerative, agglomerative, agglomerative], [sequential, sequential, sequential, sequential, sequential]]
  sparsity_scheme: [[2, 10, 25, 45, 70]]

  
